### ISSUE TITLE
html-webpack-plugin dependency has node version mismatch

### ISSUE THREAD

**Issue by jantimon** [DanielRuf/html-minifier-terser#22]
webpack 4 supports node 6.x

therefore html-webpack-plugin tries to do the same.

html-minifier also supports node 6.x https://github.com/kangax/html-minifier/blob/51ce10f4daedb1de483ffbcccecc41be1c873da2/package.json#L50

also terser supports node 6.x
https://github.com/terser/terser/blob/6589965fe372124ce94410c9e0e7389732a3c8ea/package.json#L9

unfortunately html-minfier-terser is not compatible to the webpack 4 eco system:
https://github.com/DanielRuf/html-minifier-terser/blob/47cbb36f294dd49e20779213be721238a80f6c47/package.json#L52

is there any way to support node 6.x?

See also https://github.com/jantimon/html-webpack-plugin/issues/1313

**Comment by DanielRuf** [comment]
Afaik there was a reason for that. See https://github.com/DanielRuf/html-minifier-terser/commit/9aa238e5f1420939f62d37f970d5bf21017931a6

Let me quickly check if it was only because of my security policy (NodeJS 6 has already reached its EOL a few months ago) or because of another reason.

**Comment by DanielRuf** [comment]
See https://travis-ci.com/DanielRuf/html-minifier-terser/jobs/255495856#L693

I guess this was never tested on the original `html-minifier` project.

**Comment by DanielRuf** [comment]
I will try to find a solution.

**Comment by jantimon** [comment]
Maybe we can skip eslint for node 6?

**Comment by DanielRuf** [comment]
This is not the main issue. After fixing this `node-qunit-puppeteer` produces the next issue because of the usage of `async`.

**Comment by DanielRuf** [comment]
Also NodeJS 6 is not recommended for webpack 4, see https://twitter.com/wSokra/status/967852475918274561.

I will skip the unit tests for NodeJS 6 as these were never really running on the original repository.

**Comment by DanielRuf** [comment]
html-minifier-terser v5.0.2 is released and the `engines.node` change is reverted now.

**Comment by jantimon** [comment]
Thanks a lot 👍

<img width="242" alt="webpack" src="https://user-images.githubusercontent.com/4113649/68657210-8f11c980-0533-11ea-8108-3985ab21c224.png">

But You are right node 6 is not the recommended version it is just the compatible version. 
As unfortunately many systems and local environments are still using it.

For Webpack 5 the node version will be increased:

```
"engines": {
    "node": ">=10.13.0"
  },
```

**Comment by DanielRuf** [comment]
Closing as resolved as the latest release should work with NodeJS 6 without stopping the installation due to the previous engine setting.
