### ISSUE TITLE
after set "conservativeCollapse: false", still leave a white space between html elements

### ISSUE THREAD

**Issue by snoleo** [DanielRuf/html-minifier-terser#26]
## Expected behaviour
with "conservativeCollapse: false", it should remove white spaces between html elements entirely.
```html
<div><a href="#">123</a><a href="#">456</a><a href="#">test 3</a></div>
```
## Current behaviour
Still leave a white space between html elements.
```html
<div><a href="#">123</a> <a href="#">456</a> <a href="#">test 3</a></div>
```
## Environment

```
Node.js v12.14.0
linux 5.0.0-37-generic
npm 6.13.4
webpack@4.41.4
html-webpack-plugin@3.2.0
```

### Config

```js
  plugins: [
    new HtmlWebpackPlugin({
      chunks: ['index'],
      template: './src/index.html',
      filename: './index.html',
      minify: { removeComments: true, removeEmptyAttributes: true, removeRedundantAttributes: false, collapseWhitespace: true, conservativeCollapse: false }
    }),
    new HtmlWebpackPlugin({
      chunks: ['sub'],
      template: './src/sub.html',
      filename: './sub.html',
      minify: { removeComments: true, removeEmptyAttributes: true, removeRedundantAttributes: false, collapseWhitespace: true, conservativeCollapse: false }
    })
  ],
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
                <div>
                        <a href="#">123</a>
                        <a href="#">456</a>
                        <a href="#">test 3</a>
                </div>
    </body>
</html>
```

**Comment by DanielRuf** [comment]
> with "conservativeCollapse: false", it should remove white spaces between html elements entirely.

Normally not, also see https://github.com/kangax/html-minifier/issues/834

Removing the spaces between your anchors would create a different output which is broken then.

http://perfectionkills.com/experimenting-with-html-minifier/#cost_and_benefits

**Comment by DanielRuf** [comment]
https://github.com/DanielRuf/html-minifier-terser/blob/583e0861ee852a76acb1e8ec00b3de35a024927d/src/htmlminifier.js#L66-L69

https://github.com/DanielRuf/html-minifier-terser/blob/583e0861ee852a76acb1e8ec00b3de35a024927d/src/htmlminifier.js#L76

https://github.com/DanielRuf/html-minifier-terser/blob/583e0861ee852a76acb1e8ec00b3de35a024927d/src/htmlminifier.js#L80

https://github.com/DanielRuf/html-minifier-terser/blob/583e0861ee852a76acb1e8ec00b3de35a024927d/src/htmlminifier.js#L1131

https://github.com/DanielRuf/html-minifier-terser/blob/583e0861ee852a76acb1e8ec00b3de35a024927d/src/htmlminifier.js#L1172

**Comment by DanielRuf** [comment]
Closing as there is no further feedback.
