### ISSUE TITLE
how to keep invalid css as is

### ISSUE THREAD

**Issue by evilebottnawi** [DanielRuf/html-minifier-terser#27]
For example we have the code and set the `minifyCSS` option to `true`:
```
<div style="invalid css here">test</div>
```

Output:
```
<div style="">Foo</div>
```

Will be great keep invalid css as is and do not remove him.

ref: https://github.com/webpack-contrib/html-loader/issues/213

**Comment by DanielRuf** [comment]
The issue comes from https://github.com/jakubpawlowicz/clean-css

I suggest to check the issues and PRs there.

I see no other option than forking this too or switching to another library. And if so which one?

**Comment by DanielRuf** [comment]
I will check later if this is the case that the css library changes this.

**Comment by DanielRuf** [comment]
Yes, it's done by the minify-css library, see https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L285

**Comment by DanielRuf** [comment]
Yes, it's done by the minify-css library, see https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L285 and https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L677-681

**Comment by DanielRuf** [comment]
Yes, it's done by the minify-css library, see https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L285 and https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L677-L681

**Comment by DanielRuf** [comment]
Yes, it's done by the clean-css library, see https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L285 and https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L677-L681

**Comment by DanielRuf** [comment]
`csso` will not be an option. See https://github.com/css/csso/issues/333

> It's quite complicated to parse invalid CSS

This also applies to `clean-css`.

There is a way to prevent that:
https://github.com/jakubpawlowicz/clean-css#how-to-keep-a-css-fragment-intact

This is already supported through `clean-css`.
Use the `/* clean-css ignore:start */` and `/* clean-css ignore:end */` comments.

`<div style="/* clean-css ignore:start */invalid css here/* clean-css ignore:end */">test</div>`

<img width="832" alt="Bildschirmfoto 2020-01-22 um 00 50 36" src="https://user-images.githubusercontent.com/827205/72853314-5586d880-3cb1-11ea-8bd1-95b85d11fbf8.png">

**Comment by DanielRuf** [comment]
I think this should be at least documented.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/html-loader/issues/213#issuecomment-577073822

I think we should open issue in clean-css (maybe migrate on other solution). I expect what clean-css throw an error if something wrong with syntax instead return empty string, it is js, not php :smile:

**Comment by DanielRuf** [comment]
> I think we should open issue in clean-css (maybe migrate on other solution). I expect what clean-css throw an error if something wrong with a syntax instead return an empty string

Definitely.
https://github.com/jakubpawlowicz/clean-css/issues/847

This makes probably more sense as it does not throw an error here as it seems. Otherwise it would return the content unchanged.

See https://github.com/DanielRuf/html-minifier-terser/blob/991decf66d180a924160c8c9788efd23a12d4028/src/htmlminifier.js#L682-L685

![grafik](https://user-images.githubusercontent.com/827205/72880034-5eea6200-3cfe-11ea-880b-c003dee77706.png)

![grafik](https://user-images.githubusercontent.com/827205/72880099-85100200-3cfe-11ea-895b-d2f2fae47c4f.png)


https://www.npmjs.com/package/clean-css#minify-method

> it is js, not php smile

Not sure what you mean with this.

**Comment by evilebottnawi** [comment]
> This makes probably more sense as it does not throw an error here as it seems. Otherwise it would return the content unchanged.

What about keep an original code if error more than one?

> Not sure what you mean with this.

Just joke, PHP functions return an empty string instead throw an error in mane cases :small_airplane:

**Comment by DanielRuf** [comment]
> What about keep an original code if error more than one?

Not sure why you would want to do this. It already checks `length > 0`.
I see no task on my side here at the moment.

> Just joke, PHP functions return an empty string instead throw an error in mane cases small_airplane

Depends on how it is programmed. And there is a strict mode too. Same in other languages too.

**Comment by DanielRuf** [comment]
> What about keep an original code if error more than one?

Not sure why you would want to do this. It already checks `cleanCssOutput.errors.length > 0`.
I see no task on my side here at the moment.

> Just joke, PHP functions return an empty string instead throw an error in mane cases small_airplane

Depends on how it is programmed. And there is a strict mode too. Same in other languages too.

**Comment by DanielRuf** [comment]
Should be handled by the upstream dependency which is clean-css (probably through an option) so this should be reported there. html-minifier itself does not handle / catch these errors and just applies clean-css and simply outputs the errors if there are any.

Same applies to html: https://github.com/DanielRuf/html-minifier-terser#working-with-invalid-markup

Invalid code (totally wrong CSS and HTML) implies a bigger problem. And as stated in https://github.com/DanielRuf/html-minifier-terser/issues/27#issuecomment-576941923 there is a workaround in clean-css.
