### ISSUE TITLE
options

### ISSUE THREAD

**Issue by da0ka** [DanielRuf/html-minifier-terser#42]
could you add options of js/css minifier for test page(https://danielruf.github.io/html-minifier-terser)

**Comment by DanielRuf** [comment]
Hi @da0ka,

so far the test page uses only a few of the available options and it is only a small test page.

Which exact options do you want to use there that you can not try with on https://repl.it/languages/nodejs?

**Comment by DanielRuf** [comment]
Closing as there was no feedback so far.
Feel free to mention the options that you miss.

Also the css (clean-css) and js minifier (terser) have their own documentation.
